apiVersion: v1
kind: Namespace
metadata:
  name: qflow-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qflow-operator-sa
  namespace: qflow-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qflow-operator-role
rules:
  - apiGroups: ["qflow.io"]
    resources: ["quantumworkflows", "quantumworkflows/status", "quantumworkflow"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # give full permissions for debugging
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "" ]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qflow-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qflow-operator-role
subjects:
  - kind: ServiceAccount
    name: qflow-operator-sa
    namespace: qflow-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qflow-operator
  namespace: qflow-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qflow-operator
  template:
    metadata:
      labels:
        app: qflow-operator
    spec:
      serviceAccountName: qflow-operator-sa
      containers:
        - name: operator
          # IMPORTANT: Replace this with the name of your container image
          image: docker.io/local/qflow-operator
          imagePullPolicy: IfNotPresent
          env:
            # Enable verbose logging
            - name: RUST_LOG
              value: "info,kube=debug"